version: '3.7'
services:

  bot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - release_version=docker-compose
    image: lukaswire/digital-signatures-be
    container_name: digital-signatures-be
    env_file: .env
    ports:
      - 8080:8080
