version: '3.7'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - release_version=docker-compose
    image: lukaswire/polls
    container_name: poll-bot
    env_file: .env
    ports:
      - 8080:8080
    networks:
      - poll-bot-net
    depends_on:
      - db

  db:
    image: postgres:12.2
    container_name: poll-bot-db
    env_file: .env
    ports:
      - 5432:5432
    networks:
      - poll-bot-net
    volumes:
      - poll-bot-db:/var/lib/postgresql/data/


networks:
  poll-bot-net:
    driver: bridge

volumes:
  poll-bot-db:
