version: '3.7'
services:
  ganymede:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - release_version=docker-compose
    image: lukaswire/ganymede
    container_name: ganymede
    volumes:
      - ./certificates:/certificates
    env_file: certificates/aves.env
    environment:
      - STORE_PATH=/certificates/aves.jks
    ports:
      - 8080:8080
