version: '3.3'
services:
  bot:
    build:
      context: ../
      dockerfile: Dockerfile
    image: lukaswire/polls-integration
    container_name: poll-bot-integration
    env_file: .env-integration
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - bot-integration-tests-network

  integration-tests:
    build:
      context: .
      dockerfile: Dockerfile
    image: lukaswire/polls-integration-tests
    container_name: poll-bot-integration-tests
    env_file: .env-integration
    ports:
      - 8081:8081
    depends_on:
      - bot
    networks:
      - bot-integration-tests-network

  db:
    image: postgres:12.2
    container_name: poll-bot-db-integration-tests
    env_file: .env-integration
    ports:
      - 5432:5432
    networks:
      - bot-integration-tests-network

networks:
  bot-integration-tests-network:
    driver: bridge
